id = "mcp-server-vercel"
name = "Vercel MCP Server"
authors = ["David C Cavalcante <davcavalcante@proton.me>", "Takk™ Innovate Studio <say@takk.ag>"]
version = "1.0.0"
schema_version = 1
description = "💾 Model Context Protocol (MCP) Server for Vercel"
repository = "https://github.com/Takk8IS/vercel-mcp-server-theme-for-zed"

[context_servers.mcp-server-vercel]
name = "Vercel MCP Server"
